TOKEN = ''
PAYMENTS_TOKEN = ''
PONI_BOT = 'GPT-Dialog' 
SHOP_ID = ''
SHOP_API_TOKEN = ''
SHOP_EMAIL =''
DB_FILE = 'db/db.db'

p = ''
OPENAIKEY = ''

STATUS = 0

DAYS_ADD_TO_PAYMENT = 30
DAYS_ADD_FOR_REFFERAL = 5
DAYS_FREE_USE = 1
DAYS_FREE_REFFERAL = 1
DAYS_REMINDER = 5
